version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendNYG
    container_name: frontendNYG
    ports:
      - "3110:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebNYG

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendNYG
    container_name: backendNYG
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8110:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebNYG

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebNYG
    container_name: webNYG
    ports:
      - "85:80" # si tienes problemas con el puerto 80 cambia el puerto externo aquí
    networks:
      - redwebNYG

networks:
  redwebNYG:
    driver: bridge
